// Generated by LiveScript 1.2.0
var ref$, div, script, Timeline;
ref$ = React.DOM, div = ref$.div, script = ref$.script;
Timeline = React.createClass({
  getDefaultProps: function(){
    return {
      id: 'timeline-embed',
      source: null,
      width: 800,
      height: 600
    };
  },
  render: function(){
    return div({
      id: this.props.id
    }, null);
  },
  componetDidMount: function(){
    script({
      src: 'http://cdn.knightlab.com/libs/timeline/latest/js/storyjs-embed.js'
    }, null);
    document.head.append(script);
    return createStoryJS({
      type: 'timeline',
      width: this.props.width,
      height: this.props.height,
      source: this.props.source,
      embed_id: this.props.id
    });
  }
});