// Generated by LiveScript 1.2.0
(function(){
  window.init = function(){
    var url;
    url = 'https://docs.google.com/spreadsheet/pub?key=0Agl_Dv6iEbDadHdKcHlHcTB5bzhvbF9iTWwyMmJHdkE&amp;output=html';
    return React.renderComponent(Timeline({
      width: '100%',
      source: url
    }), document.body);
  };
}).call(this);
